name: Twice Daily Rebuild
on:
  schedule:
    - cron: "0 5 * * *"   # 8 AM East Africa Time (5:00 UTC)
    - cron: "0 17 * * *"  # 8 PM East Africa Time (17:00 UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
